---
- name: Installing Nextcloud from https://github.com/flor0/nextcloud-docker
  hosts: nextcloud
  become: yes

  vars:
    # Change these variables to your setup
    # Make sure they are the same in prepare.yml
    mariadb_pass: password123
    mariadb_root_pass: password123
    data_dir: /srv/nextcloud/data
    nextcloud_root: /srv/nextcloud
    docker_dir: /srv/nextcloud-docker
    docker_compose_dir: /srv/nextcloud-docker/nextcloud

  tasks:
    - name: "Ensure {{ docker_dir }} exists"
      ansible.builtin.file:
        path: "{{ docker_dir }}"
        state: directory
        mode: '0755'
    - name: Git clone Nextcloud Docker
      ansible.builtin.git:
        repo: https://github.com/flor0/nextcloud-docker.git
        dest: "{{ docker_compose_dir }}"
    - name: Configuring .env by writing to it
      ansible.builtin.copy:
        content: |
          DATA_DIR={{ data_dir }}
          NEXTCLOUD_DIR={{ nextcloud_dir }}/nextcloud
          MARIADB_ROOT_PASS={{ mariadb_root_pass }}
          MARIADB_PASS={{ mariadb_pass }}
        dest: "~{{ docker_compose_dir }}/.env"
    - name: Running docker-compose build php-fpm-nextcloud
      ansible.builtin.command:
        cmd: "docker compose -f {{ docker_compose_dir }}/docker-compose.yml build php-fpm-nextcloud"
    - name: Running docker-compose up -d
      ansible.builtin.command:
        cmd: "docker compose -f {{ docker_compose_dir }}/docker-compose.yml up -d"

